// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ_Fdbq2SpnOCr4phA_WS2u4le5r71cAE',
    appId: '1:97485744209:android:46405e08a1532b25953070',
    messagingSenderId: '97485744209',
    projectId: 'chattingapp-2e8cd',
    storageBucket: 'chattingapp-2e8cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3txEn5YPpLgvFBgoOW0_7_3bJdKSJwGo',
    appId: '1:97485744209:ios:fc9bc773bfa84626953070',
    messagingSenderId: '97485744209',
    projectId: 'chattingapp-2e8cd',
    storageBucket: 'chattingapp-2e8cd.appspot.com',
    androidClientId: '97485744209-4ji3vrqjnoc9ah17ufl5f4cflc3l3uu1.apps.googleusercontent.com',
    iosClientId: '97485744209-49gddjdr8prdan4lngjuh1vgmutq8vms.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
